name: Construir APK Android (Node 22)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js (Actualizado)
        uses: actions/setup-node@v4
        with:
          node-version: '22' # <--- ¡AQUÍ ESTABA EL CULPABLE! Cambiado de 20 a 22.

      - name: 3. Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 4. Instalar dependencias
        run: npm install

      - name: 5. Construir React
        run: npm run build

      - name: 6. Crear entorno Android
        # Forzamos la instalación y creación de Android
        run: |
          npm install @capacitor/android
          npx cap add android

      - name: 7. Permisos de Gradle
        run: |
          cd android
          chmod +x gradlew

      - name: 8. Construir APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: 9. Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: nexmark
          path: android/app/build/outputs/apk/debug/app-debug.apk
